# -*- coding: utf-8 -*-
"""Sanskrit_to_English_NMT_Assignment-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhAvUwxQ8IRySPzv4RZFu4ZbsQdo0_x-

# Assignment 2 — Sanskrit-to-English Neural Machine Translation

This notebook implements a **custom sequence-to-sequence NMT system** using:

- Unicode-aware preprocessing
- Separate Sanskrit and English word vocabularies
- Bidirectional GRU encoder
- Bahdanau additive attention
- GRU decoder
- Teacher forcing, gradient clipping, padding-aware loss
- Greedy decoding
- BLEU evaluation
- Optional BERTScore evaluation
- Attention visualization
- Interactive inference demo

The supplied train/dev/test files are aligned by `Source_id`.
"""

# If running in Colab, uncomment:
# !pip -q install sacrebleu bert-score

import os, re, math, random, unicodedata, time
from collections import Counter
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
import os

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", DEVICE)

#DATA_DIR = "/content" if os.path.exists("/content/train_sa_10000.csv") else "/mnt/data"
#print("DATA_DIR:", DATA_DIR)

# Mount Google Drive
drive.mount('/content/drive')

# Folder containing all CSV files
DATA_DIR = "/content/drive/MyDrive/NLU_Assignment"

# Verify files
print(os.listdir(DATA_DIR))

def load_split(split, n):
    sa = pd.read_csv(f"{DATA_DIR}/{split}_sa_{n}.csv")
    en = pd.read_csv(f"{DATA_DIR}/{split}_en_{n}.csv")
    assert sa["Source_id"].is_unique and en["Source_id"].is_unique
    df = sa.merge(en, on="Source_id", how="inner", validate="one_to_one")
    assert len(df) == n, (split, len(df), n)
    return df

train_df = load_split("train", 10000)
dev_df   = load_split("dev", 1000)
test_df  = load_split("test", 1000)

print(train_df.shape, dev_df.shape, test_df.shape)
display(train_df.head())

# Data checks
for name, df in [("train",train_df),("dev",dev_df),("test",test_df)]:
    print(name,
          "null_sa=", df.Sentence_sa.isna().sum(),
          "null_en=", df.Sentence_en.isna().sum(),
          "duplicate_sa=", df.Sentence_sa.duplicated().sum(),
          "duplicate_en=", df.Sentence_en.duplicated().sum())

# Unicode-aware tokenization.
# Sanskrit: whitespace + punctuation separation; English: words/numbers/punctuation.
PUNCT_RE = re.compile(r'([।॥!?.,;:"()\[\]{}])')

def normalize_text(s):
    s = unicodedata.normalize("NFC", str(s))
    s = re.sub(r"\s+", " ", s).strip()
    return s

def tokenize_sa(s):
    s = normalize_text(s)
    s = PUNCT_RE.sub(r" \1 ", s)
    return s.split()

def tokenize_en(s):
    s = normalize_text(s).lower()
    return re.findall(r"[a-z]+(?:'[a-z]+)?|\d+(?:\.\d+)?|[^\w\s]", s, flags=re.UNICODE)

print(tokenize_sa(train_df.Sentence_sa.iloc[0]))
print(tokenize_en(train_df.Sentence_en.iloc[0]))

SPECIALS = ["<pad>", "<unk>", "<bos>", "<eos>"]

class Vocab:
    def __init__(self, token_lists, min_freq=2, max_size=None):
        c = Counter(t for xs in token_lists for t in xs)
        words = [w for w,f in c.most_common() if f >= min_freq]
        if max_size: words = words[:max_size-len(SPECIALS)]
        self.itos = SPECIALS + [w for w in words if w not in SPECIALS]
        self.stoi = {w:i for i,w in enumerate(self.itos)}
        self.pad, self.unk, self.bos, self.eos = [self.stoi[x] for x in SPECIALS]
    def encode(self, toks, add_bos_eos=True):
        ids = [self.stoi.get(t, self.unk) for t in toks]
        return ([self.bos]+ids+[self.eos]) if add_bos_eos else ids
    def decode(self, ids):
        out=[]
        for i in ids:
            w=self.itos[int(i)]
            if w=="<eos>": break
            if w not in SPECIALS: out.append(w)
        return out
    def __len__(self): return len(self.itos)

sa_train_tok = [tokenize_sa(x) for x in train_df.Sentence_sa]
en_train_tok = [tokenize_en(x) for x in train_df.Sentence_en]

SRC = Vocab(sa_train_tok, min_freq=2, max_size=30000)
TRG = Vocab(en_train_tok, min_freq=2, max_size=30000)
print("Sanskrit vocab:", len(SRC), "English vocab:", len(TRG))

MAX_SRC_LEN = 80
MAX_TRG_LEN = 80

class ParallelDataset(Dataset):
    def __init__(self, df):
        self.df=df.reset_index(drop=True)
    def __len__(self): return len(self.df)
    def __getitem__(self,i):
        r=self.df.iloc[i]
        s=SRC.encode(tokenize_sa(r.Sentence_sa))[:MAX_SRC_LEN]
        t=TRG.encode(tokenize_en(r.Sentence_en))[:MAX_TRG_LEN]
        if s[-1] != SRC.eos: s[-1]=SRC.eos
        if t[-1] != TRG.eos: t[-1]=TRG.eos
        return torch.tensor(s), torch.tensor(t)

def collate(batch):
    ss,tt=zip(*batch)
    ss=nn.utils.rnn.pad_sequence(ss,batch_first=True,padding_value=SRC.pad)
    tt=nn.utils.rnn.pad_sequence(tt,batch_first=True,padding_value=TRG.pad)
    return ss,tt

train_loader=DataLoader(ParallelDataset(train_df),batch_size=64,shuffle=True,collate_fn=collate)
dev_loader=DataLoader(ParallelDataset(dev_df),batch_size=64,shuffle=False,collate_fn=collate)

class Encoder(nn.Module):
    def __init__(self, vocab, emb=256, hid=256, dropout=.3):
        super().__init__()
        self.emb=nn.Embedding(vocab,emb,padding_idx=SRC.pad)
        self.rnn=nn.GRU(emb,hid,batch_first=True,bidirectional=True)
        self.fc=nn.Linear(hid*2,hid)
        self.drop=nn.Dropout(dropout)
    def forward(self,x):
        e=self.drop(self.emb(x))
        out,h=self.rnn(e)
        h=torch.tanh(self.fc(torch.cat([h[-2],h[-1]],dim=1)))
        return out,h

class BahdanauAttention(nn.Module):
    def __init__(self, enc_hid=256, dec_hid=256):
        super().__init__()
        self.W=nn.Linear(enc_hid*2,dec_hid)
        self.U=nn.Linear(dec_hid,dec_hid)
        self.v=nn.Linear(dec_hid,1,bias=False)
    def forward(self,h,enc_out,mask):
        score=self.v(torch.tanh(self.W(enc_out)+self.U(h).unsqueeze(1))).squeeze(-1)
        score=score.masked_fill(~mask,-1e9)
        return F.softmax(score,dim=1)

class Decoder(nn.Module):
    def __init__(self,vocab,emb=256,enc_hid=256,dec_hid=256,dropout=.3):
        super().__init__()
        self.emb=nn.Embedding(vocab,emb,padding_idx=TRG.pad)
        self.attn=BahdanauAttention(enc_hid,dec_hid)
        self.rnn=nn.GRU(emb+enc_hid*2,dec_hid,batch_first=True)
        self.fc=nn.Linear(dec_hid+enc_hid*2+emb,vocab)
        self.drop=nn.Dropout(dropout)
    def forward(self,y,h,enc_out,mask):
        e=self.drop(self.emb(y)).unsqueeze(1)
        a=self.attn(h,enc_out,mask)
        ctx=torch.bmm(a.unsqueeze(1),enc_out)
        o,h2=self.rnn(torch.cat([e,ctx],dim=2),h.unsqueeze(0))
        logits=self.fc(torch.cat([o.squeeze(1),ctx.squeeze(1),e.squeeze(1)],dim=1))
        return logits,h2.squeeze(0),a

class Seq2Seq(nn.Module):
    def __init__(self,enc,dec):
        super().__init__(); self.enc=enc; self.dec=dec
    def forward(self,src,trg,teacher_forcing=.5):
        enc_out,h=self.enc(src); mask=src.ne(SRC.pad)
        y=trg[:,0]; outs=[]
        for t in range(1,trg.size(1)):
            logits,h,_=self.dec(y,h,enc_out,mask)
            outs.append(logits.unsqueeze(1))
            y = trg[:,t] if random.random()<teacher_forcing else logits.argmax(1)
        return torch.cat(outs,1)

model=Seq2Seq(Encoder(len(SRC)),Decoder(len(TRG))).to(DEVICE)
print("Parameters:", sum(p.numel() for p in model.parameters() if p.requires_grad))

criterion=nn.CrossEntropyLoss(ignore_index=TRG.pad)
optimizer=torch.optim.AdamW(model.parameters(),lr=3e-4,weight_decay=1e-5)

def run_epoch(loader,train=True,tf=.5):
    model.train(train); total=0
    for src,trg in loader:
        src,trg=src.to(DEVICE),trg.to(DEVICE)
        if train: optimizer.zero_grad()
        with torch.set_grad_enabled(train):
            out=model(src,trg,teacher_forcing=tf if train else 0.0)
            loss=criterion(out.reshape(-1,out.size(-1)),trg[:,1:].reshape(-1))
            if train:
                loss.backward()
                nn.utils.clip_grad_norm_(model.parameters(),1.0)
                optimizer.step()
        total += loss.item()*src.size(0)
    return total/len(loader.dataset)

EPOCHS=10
PATIENCE=4
best=float("inf"); bad=0
history=[]
for ep in range(1,EPOCHS+1):
    tr=run_epoch(train_loader,True,tf=max(.2,.7-ep*.025))
    dv=run_epoch(dev_loader,False)
    history.append((ep,tr,dv))
    print(f"Epoch {ep:02d} train={tr:.4f} dev={dv:.4f}")
    if dv < best:
        best=dv; bad=0
        torch.save({"model":model.state_dict(),"src_itos":SRC.itos,"trg_itos":TRG.itos},
                   "best_sanskrit_en_nmt.pt")
    else:
        bad+=1
        if bad>=PATIENCE:
            print("Early stopping"); break

model.load_state_dict(torch.load("best_sanskrit_en_nmt.pt",map_location=DEVICE)["model"])

@torch.no_grad()
def translate(sentence,max_len=80):
    model.eval()
    toks=tokenize_sa(sentence)
    ids=SRC.encode(toks)[:MAX_SRC_LEN]
    if ids[-1]!=SRC.eos: ids[-1]=SRC.eos
    src=torch.tensor(ids).unsqueeze(0).to(DEVICE)
    enc_out,h=model.enc(src); mask=src.ne(SRC.pad)
    y=torch.tensor([TRG.bos],device=DEVICE)
    pred=[]; attns=[]
    for _ in range(max_len):
        logits,h,a=model.dec(y,h,enc_out,mask)
        nxt=logits.argmax(1).item()
        if nxt==TRG.eos: break
        pred.append(nxt); attns.append(a.squeeze(0).cpu().numpy())
        y=torch.tensor([nxt],device=DEVICE)
    return " ".join(TRG.decode(pred)), toks, np.array(attns)

for i in range(5):
    r=dev_df.iloc[i]
    hyp,_,_=translate(r.Sentence_sa)
    print("SA :",r.Sentence_sa)
    print("REF:",r.Sentence_en)
    print("HYP:",hyp,"\n")

# Commented out IPython magic to ensure Python compatibility.
#!pip install -q sacrebleu
# %pip install -q sacrebleu bert-score

# Corpus BLEU
import sacrebleu

def predict_df(df):
    return [translate(s)[0] for s in df.Sentence_sa]

dev_hyp=predict_df(dev_df)
test_hyp=predict_df(test_df)

dev_bleu=sacrebleu.corpus_bleu(dev_hyp,[dev_df.Sentence_en.tolist()])
test_bleu=sacrebleu.corpus_bleu(test_hyp,[test_df.Sentence_en.tolist()])
print("Dev BLEU :",dev_bleu.score)
print("Test BLEU:",test_bleu.score)

#%pip install -q sacrebleu bert-score

import torch
import numpy as np
import pandas as pd
import transformers

print("torch:", torch.__version__)
print("numpy:", np.__version__)
print("pandas:", pd.__version__)
print("transformers:", transformers.__version__)

# Generate predictions for the complete test dataset
def predict_df(df):
    predictions = []

    for i, sentence in enumerate(df["Sentence_sa"]):
        prediction, _, _ = translate(str(sentence))
        predictions.append(prediction)

        if (i + 1) % 100 == 0:
            print(f"Translated {i + 1}/{len(df)} sentences")

    return predictions


test_hyp = predict_df(test_df)

print("Number of predictions:", len(test_hyp))
print("First 5 predictions:")
for x in test_hyp[:5]:
    print(x)

# Generate test predictions first
test_hyp = predict_df(test_df)

# Create submission.csv
submission_df = pd.DataFrame({
    "Source_id": test_df["Source_id"],
    "Sentence_en": test_hyp
})

submission_df.to_csv("submission.csv", index=False)

print("submission.csv created successfully")
print("Location:", os.path.abspath("submission.csv"))

display(submission_df.head())

from bert_score import score

P, R, F1 = score(
    test_hyp,
    test_df["Sentence_en"].astype(str).tolist(),
    model_type="bert-base-multilingual-cased",
    verbose=True,
    device="cuda" if torch.cuda.is_available() else "cpu"
)

print(f"Precision: {P.mean().item():.4f}")
print(f"Recall:    {R.mean().item():.4f}")
print(f"F1:        {F1.mean().item():.4f}")

# Attention visualization
def plot_attention(sentence):
    hyp,src_toks,A=translate(sentence)
    trg_toks=tokenize_en(hyp)
    if len(A)==0:
        print("Empty translation"); return
    plt.figure(figsize=(max(7,len(src_toks)*.7),max(4,len(trg_toks)*.5)))
    plt.imshow(A[:len(trg_toks),:len(src_toks)+2],aspect="auto")
    plt.xticks(range(len(src_toks)+2),["<bos>"]+src_toks+["<eos>"],rotation=60,ha="right")
    plt.yticks(range(len(trg_toks)),trg_toks)
    plt.xlabel("Sanskrit source"); plt.ylabel("English output")
    plt.colorbar(label="Attention weight")
    plt.tight_layout(); plt.show()
    print("Translation:",hyp)

plot_attention(test_df.Sentence_sa.iloc[0])

# Error analysis table
analysis_rows=[]
for i in range(20):
    r=test_df.iloc[i]
    analysis_rows.append({
        "Source_id":r.Source_id,
        "Sanskrit":r.Sentence_sa,
        "Reference":r.Sentence_en,
        "Prediction":test_hyp[i]
    })
error_df=pd.DataFrame(analysis_rows)
display(error_df)
error_df.to_csv("error_analysis.csv",index=False)

# Final interactive inference demo
while True:
    s=input("Enter Sanskrit sentence (or 'quit'): ").strip()
    if s.lower()=="quit": break
    print("English:",translate(s)[0])

"""## Discussion / Error Analysis

Typical errors expected for this low-resource, morphologically rich setting:

1. **Rare inflected forms → `<unk>` or lexical substitution.** Word-level vocabulary cannot fully cover Sanskrit's productive morphology.
2. **Long sentences → omissions/repetitions.** A recurrent decoder can lose global context despite attention.
3. **Free word order → alignment ambiguity.** Sanskrit grammatical roles are strongly marked by case endings rather than fixed position.
4. **Named entities and transliterations → inconsistent rendering.**
5. **Domain mixture → terminology errors.** The supplied examples include technical/computing text alongside general prose.

Likely improvements: subword tokenization (SentencePiece/BPE), beam search, label smoothing, tied embeddings where appropriate, larger training data, and a Transformer trained from scratch if compute permits.

"""
